import { dirname, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { config } from "@dotenvx/dotenvx";
import { createEnv } from "@t3-oss/env-core";
import { isProduction } from "std-env";
import { z } from "zod";

console.debug("⏳ [ENV_SERVER] Loading environment variables...", {
  SOURCE_COMMIT: process.env.SOURCE_COMMIT,
  VITE_SERVER_URL: process.env.VITE_SERVER_URL,
  VITE_WEB_URL: process.env.VITE_WEB_URL,
});

config({
  ignore: ["MISSING_ENV_FILE"],
  path: resolve(dirname(fileURLToPath(import.meta.url)), "../../.env"),
});

export const ENV_SERVER = createEnv({
  emptyStringAsUndefined: true,
  runtimeEnv: process.env,
  server: {
    VITE_SERVER_URL: isProduction ? z.url() : z.url().default("http://localhost:5000/server"),
    VITE_WEB_URL: isProduction ? z.url() : z.url().default("http://localhost:3000/web"),
    DATABASE_URL: z.string().min(1),
    BETTER_AUTH_SECRET: z.string().min(32),
    NODE_ENV: z.enum(["development", "production"]).default("development"),
    SOURCE_COMMIT: z.string().min(1).default("unknown"), // autogenerated by Coolify, needs to be manually set otherwise
    ENABLE_OPEN_API_DOCS: z.stringbool().default(false),
  },
});

console.debug("✅ [ENV_SERVER] Successfully loaded environment variables.");
